### ISSUE TITLE
Building Error help??

### ISSUE THREAD

**Issue by SfrancyDev** [armin-reichert/pacman#2]
Dear,
i'm trying to compile your code(i wanna study it and make some changes), but i have this compilation errror:
Missing artifact de.amr.easy.game:EasyGame:jar:0.0.1-SNAPSHOT	pom.xml	/PacManGame	line 40	Maven Dependency Problem
Missing artifact de.amr.graph:Graph:jar:0.0.1-SNAPSHOT	pom.xml	/PacManGame	line 50	Maven Dependency Problem
Missing artifact de.amr.statemachine:StateMachine:jar:0.0.1-SNAPSHOT	pom.xml	/PacManGame	line 45	Maven Dependency Problem
The container 'Maven Dependencies' references non existing library '/Users/iatcompany/.m2/repository/de/amr/easy/game/EasyGame/0.0.1-SNAPSHOT/EasyGame-0.0.1-SNAPSHOT.jar'	PacManGame		Build path	Build Path Problem
The project cannot be built until build path errors are resolved	PacManGame		Unknown	Java Problem

Thanks in advance for your help,
Fra.

**Comment by armin-reichert** [comment]
To build this project, you first need to build the dependent projects/repositories locally, namely "graph", "easy-game" and "statemachine". They are not available from the central Maven server(s).
