### ISSUE TITLE
Build failng

### ISSUE THREAD

**Issue by smiile** [armin-reichert/pacman#6]
Hi, I tried building the package as instructed (`mvn clean package`) But  I get the following output and can't find the address of the dependency:
```
[ERROR] Failed to execute goal on project PacManGame: Could not resolve dependencies for project de.amr.games.pacman:PacManGame:jar:1.0: Could not find artifact de.amr.easy.game:easy-game-framework:jar:1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```
Any hints on how to fix this? Thanks in advance!

**Comment by armin-reichert** [comment]
Hi,

the dependent projects are not available from Maven central but have to be built locally. 

So just clone the repository [Easy Game](https://github.com/armin-reichert/easy-game) and also [State Machine](https://github.com/armin-reichert/statemachine), build both projects with **maven clean install.** Then it should work.

Armin
